//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRK_ODUNC
    {
        public int HRK_NO { get; set; }
        public Nullable<System.DateTime> HRK_TARIH { get; set; }
        public Nullable<int> ALAN_UYE_NO { get; set; }
        public string ALINAN_KITAP_ISBN { get; set; }
        public Nullable<int> ODUNC_SURE { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIH { get; set; }
        public Nullable<System.DateTime> TESLIM_EDILMIS_TARIH { get; set; }
        public string TESLIM_EDILDI { get; set; }
    }
}
