//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRT_UYE
    {
        public int UYE_NO { get; set; }
        public string TC { get; set; }
        public string CINSIYET { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<System.DateTime> DOGUM_TARIHI { get; set; }
        public string DOGUM_YERI { get; set; }
        public string MESLEK { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
    }
}
