//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KRT_KITAP
    {
        public string ISBN { get; set; }
        public string BARKOD { get; set; }
        public string KITAP_ADI { get; set; }
        public string YAZARI { get; set; }
        public string YAYINEVI { get; set; }
        public Nullable<System.DateTime> YAYIN_TARIHI { get; set; }
        public Nullable<int> BASKI { get; set; }
        public string TUR { get; set; }
        public Nullable<int> SAYFA_SAYISI { get; set; }
        public string EBAT { get; set; }
        public string DIL { get; set; }
    }
}
